using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using ICam.Core.Protocol;
using ICam.Core.Security;

// Generates protocol/vectors/v1.json.
//
// The vectors are the only thing that proves the Swift and C# implementations
// actually agree. Each side has its own unit tests, and each side can be
// internally consistent while disagreeing with the other — a different byte
// order, a different JSON escape, a different key label — and nothing would
// catch it until two real devices failed to pair.
//
// Every input here is fixed, so the output is deterministic. Regenerating and
// getting a diff means the wire format changed, which is a decision, not an
// accident:
//
//     dotnet run --project tools/ProtocolVectors

var root = FindRepositoryRoot();
var output = Path.Combine(root, "protocol", "vectors", "v1.json");

var vectors = new JsonObject
{
    ["_comment"] = "Generated by tools/ProtocolVectors. Both implementations must reproduce every value here exactly. See docs/PROTOCOL.md.",
    ["protocolVersion"] = Wire.ProtocolVersion,
    ["framing"] = Framing(),
    ["keySchedule"] = KeySchedule(),
    ["aead"] = Aead(),
    ["handshakeJson"] = HandshakeJson(),
    ["mediaHeaders"] = MediaHeaders(),
    ["controlJson"] = ControlJson(),
};

var options = new JsonSerializerOptions
{
    WriteIndented = true,
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
};
Directory.CreateDirectory(Path.GetDirectoryName(output)!);
File.WriteAllText(output, vectors.ToJsonString(options) + "\n", new UTF8Encoding(false));
Console.WriteLine($"wrote {Path.GetRelativePath(root, output)}");
return 0;

static JsonArray Framing()
{
    var cases = new JsonArray();

    void Add(string name, Channel channel, FrameFlags flags, byte[] payload)
    {
        cases.Add(new JsonObject
        {
            ["name"] = name,
            ["channel"] = (int)channel,
            ["flags"] = (int)flags,
            ["payloadHex"] = Convert.ToHexStringLower(payload),
            ["frameHex"] = Convert.ToHexStringLower(new Frame(channel, flags, payload).Encode()),
        });
    }

    Add("empty control frame", Channel.Control, FrameFlags.EndOfMessage, []);
    Add("control frame", Channel.Control, FrameFlags.EndOfMessage, "{\"t\":\"ping\"}"u8.ToArray());
    Add("video frame", Channel.Video, FrameFlags.EndOfMessage, Enumerable.Range(0, 32).Select(i => (byte)i).ToArray());
    Add("handshake frame", Channel.Handshake, FrameFlags.EndOfMessage, "hello"u8.ToArray());
    return cases;
}

static JsonObject KeySchedule()
{
    // A fixed "shared secret" rather than a real key agreement: the vectors
    // must be reproducible, and the agreement itself is standard P-256 that
    // both platforms already get right.
    var shared = Enumerable.Range(0, 32).Select(i => (byte)(i * 7 + 1)).ToArray();
    var clientRandom = Enumerable.Range(0, 32).Select(i => (byte)(0xA0 + i)).ToArray();
    var serverRandom = Enumerable.Range(0, 32).Select(i => (byte)(0x10 + i * 3)).ToArray();

    var keys = SessionKeys.Derive(shared, clientRandom, serverRandom);

    return new JsonObject
    {
        ["sharedSecretHex"] = Convert.ToHexStringLower(shared),
        ["clientRandomHex"] = Convert.ToHexStringLower(clientRandom),
        ["serverRandomHex"] = Convert.ToHexStringLower(serverRandom),
        ["c2sKeyHex"] = Convert.ToHexStringLower(keys.ClientToServerKey),
        ["s2cKeyHex"] = Convert.ToHexStringLower(keys.ServerToClientKey),
        ["c2sSaltHex"] = Convert.ToHexStringLower(keys.ClientToServerSalt),
        ["s2cSaltHex"] = Convert.ToHexStringLower(keys.ServerToClientSalt),
        ["pairingDigits"] = keys.PairingDigits,
    };
}

static JsonArray Aead()
{
    var shared = Enumerable.Range(0, 32).Select(i => (byte)(i * 7 + 1)).ToArray();
    var clientRandom = Enumerable.Range(0, 32).Select(i => (byte)(0xA0 + i)).ToArray();
    var serverRandom = Enumerable.Range(0, 32).Select(i => (byte)(0x10 + i * 3)).ToArray();
    var keys = SessionKeys.Derive(shared, clientRandom, serverRandom);

    var cases = new JsonArray();
    using var channel = new SecureChannel(keys, ChannelRole.Initiator);

    // Sealed in order, because the counter advances across every channel in a
    // direction — which is exactly the property worth pinning down.
    (Channel Channel, byte[] Plaintext)[] sequence =
    [
        (Channel.Control, "{\"t\":\"device.info\"}"u8.ToArray()),
        (Channel.Video, Enumerable.Range(0, 48).Select(i => (byte)i).ToArray()),
        (Channel.Audio, new byte[16]),
        (Channel.Control, []),
    ];

    ulong counter = 0;
    foreach (var (ch, plaintext) in sequence)
    {
        cases.Add(new JsonObject
        {
            ["counter"] = counter,
            ["channel"] = (int)ch,
            ["plaintextHex"] = Convert.ToHexStringLower(plaintext),
            ["frameHex"] = Convert.ToHexStringLower(channel.Seal(ch, plaintext)),
        });
        counter++;
    }
    return cases;
}

static JsonArray HandshakeJson()
{
    var cases = new JsonArray();

    var hello = new ClientHello
    {
        Eph = Enumerable.Range(0, 65).Select(i => (byte)(i == 0 ? 0x04 : i)).ToArray(),
        Idk = Enumerable.Range(0, 65).Select(i => (byte)(i == 0 ? 0x04 : 200 - i)).ToArray(),
        Rnd = Enumerable.Range(0, 32).Select(i => (byte)(0xA0 + i)).ToArray(),
        Dev = new DeviceInfo
        {
            App = "1.0.0",
            Id = "0123456789abcdef0123456789abcdef",
            Model = "iPhone16,1",
            // Deliberately not ASCII, and containing a slash. Both are cases
            // where two JSON writers can legitimately differ, and where a
            // difference would break pairing for real users.
            Name = "آيفون Raeid a/b",
            Os = "18.5",
        },
    };
    cases.Add(new JsonObject
    {
        ["name"] = "client hello",
        ["encodedUtf8Hex"] = Convert.ToHexStringLower(HandshakeCodec.Encode(hello)),
        ["encodedText"] = Encoding.UTF8.GetString(HandshakeCodec.Encode(hello)),
    });

    var serverHello = new ServerHello
    {
        Eph = Enumerable.Range(0, 65).Select(i => (byte)(i == 0 ? 0x04 : i + 3)).ToArray(),
        Idk = Enumerable.Range(0, 65).Select(i => (byte)(i == 0 ? 0x04 : i + 9)).ToArray(),
        Rnd = Enumerable.Range(0, 32).Select(i => (byte)(0x10 + i * 3)).ToArray(),
        Dev = new DeviceInfo
        {
            App = "1.0.0",
            Id = "fedcba9876543210fedcba9876543210",
            Model = "Windows 11 Pro",
            Name = "RAEID-PC",
            Os = "10.0.26200",
        },
        Sig = [1, 2, 3, 4],
    };
    cases.Add(new JsonObject
    {
        ["name"] = "server hello transcript bytes",
        ["encodedUtf8Hex"] = Convert.ToHexStringLower(serverHello.TranscriptBytes()),
        ["encodedText"] = Encoding.UTF8.GetString(serverHello.TranscriptBytes()),
    });

    return cases;
}

static JsonArray MediaHeaders()
{
    var cases = new JsonArray();

    var video = new VideoFrameHeader(VideoCodec.Hevc, IsKeyframe: true, IsParameterSets: false,
                                     IsEndOfStream: false, Sequence: 1234,
                                     PtsUs: 987_654_321, DtsUs: 987_654_000);
    cases.Add(new JsonObject
    {
        ["kind"] = "video",
        ["codec"] = "hevc",
        ["isKeyframe"] = true,
        ["isParameterSets"] = false,
        ["sequence"] = 1234,
        ["ptsUs"] = 987_654_321,
        ["dtsUs"] = 987_654_000,
        ["headerHex"] = Convert.ToHexStringLower(video.Encode()),
    });

    var parameterSets = new VideoFrameHeader(VideoCodec.H264, IsKeyframe: true,
                                             IsParameterSets: true, IsEndOfStream: false,
                                             Sequence: 1, PtsUs: 0, DtsUs: 0);
    cases.Add(new JsonObject
    {
        ["kind"] = "video",
        ["codec"] = "h264",
        ["isKeyframe"] = true,
        ["isParameterSets"] = true,
        ["sequence"] = 1,
        ["ptsUs"] = 0,
        ["dtsUs"] = 0,
        ["headerHex"] = Convert.ToHexStringLower(parameterSets.Encode()),
    });

    var audio = new AudioFrameHeader(AudioCodec.PcmS16Le, Channels: 1, IsParameterSets: false,
                                     SampleRate: 48_000, Sequence: 7, PtsUs: 42);
    cases.Add(new JsonObject
    {
        ["kind"] = "audio",
        ["codec"] = "pcm_s16le",
        ["channels"] = 1,
        ["sampleRate"] = 48_000,
        ["sequence"] = 7,
        ["ptsUs"] = 42,
        ["headerHex"] = Convert.ToHexStringLower(audio.Encode()),
    });

    var bulk = new BulkFrameHeader(BulkKind.Chunk, TransferId: 3, Offset: 1_048_576);
    cases.Add(new JsonObject
    {
        ["kind"] = "bulk",
        ["bulkKind"] = "chunk",
        ["transferId"] = 3,
        ["offset"] = 1_048_576,
        ["headerHex"] = Convert.ToHexStringLower(bulk.Encode()),
    });

    return cases;
}

static JsonArray ControlJson()
{
    var cases = new JsonArray();

    // A camera state exactly as the phone would broadcast it. The C# side must
    // decode every field, and the Swift side must produce these values.
    var state = new CameraState
    {
        Version = 184,
        LensId = "back.wide",
        Zoom = 1.0,
        Width = 1920,
        Height = 1080,
        Fps = 30,
        Codec = VideoCodec.Hevc,
        Hdr = HdrMode.Auto,
        Stabilization = Stabilization.Standard,
        ExposureMode = ExposureMode.Manual,
        Iso = 80,
        ExposureDurationUs = 8333,
        WhiteBalanceMode = WhiteBalanceMode.Manual,
        WhiteBalancePreset = WhiteBalancePreset.Daylight,
        Temperature = 5600,
        Tint = -12,
        FocusMode = FocusMode.Manual,
        FocusPosition = 0.42,
        Torch = TorchMode.On,
        TorchLevel = 0.5,
        Orientation = OrientationLock.LandscapeLeft,
        // Non-zero, and one of them negative: these are the newest fields and
        // the ones most likely to be dropped on one side and not the other.
        Brightness = 0.25,
        Contrast = -0.1,
        Saturation = 0.5,
        Warmth = 0.35,
        Sharpness = -0.2,
    };
    cases.Add(new JsonObject
    {
        ["name"] = "camera.state",
        ["json"] = JsonNode.Parse(JsonSerializer.Serialize(state, ControlCodec.Options)),
    });

    cases.Add(new JsonObject
    {
        ["name"] = "camera.command",
        ["json"] = JsonNode.Parse(JsonSerializer.Serialize(new CameraCommandPayload
        {
            Base = 184,
            Set = new CameraMutation { Iso = 200, ExposureMode = ExposureMode.Manual },
        }, ControlCodec.Options)),
    });

    cases.Add(new JsonObject
    {
        ["name"] = "telemetry",
        ["json"] = JsonNode.Parse(JsonSerializer.Serialize(new TelemetryPayload
        {
            Thermal = "elevated",
            Pressure = "fair",
            Battery = 0.82,
            Power = "usb",
            StorageFreeBytes = 88_123_456_789,
            Capture = new TelemetryPayload.CaptureStats { Fps = 59.9, Dropped = 0 },
            Encoder = new TelemetryPayload.EncoderStats
            { Fps = 30.0, Bitrate = 7_900_000, LatencyUs = 4100 },
        }, ControlCodec.Options)),
    });

    return cases;
}

static string FindRepositoryRoot()
{
    var directory = new DirectoryInfo(AppContext.BaseDirectory);
    while (directory is not null)
    {
        if (Directory.Exists(Path.Combine(directory.FullName, "docs"))
            && Directory.Exists(Path.Combine(directory.FullName, "ios")))
        {
            return directory.FullName;
        }
        directory = directory.Parent;
    }
    throw new InvalidOperationException("could not locate the repository root");
}
